---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: maestro
    environment: dev
  name: maestro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maestro
  template:
    metadata:
      labels:
        app: maestro
        version: 0.0.1
    spec:
      containers:
      - image: ghcr.io/caju-rocks/maestro:0.0.1
        imagePullPolicy: IfNotPresent
        name: maestro
